# ============================================================
# POSTGRESQL - NEON
# ============================================================
#db.url=jdbc:postgresql://ep-restless-hall-aehwldwn-pooler.c-2.us-east-2.aws.neon.tech:5432/sysventas?sslmode=require
db.url=jdbc:postgresql://ep-fancy-glade-b449nr5t-pooler.c-6.us-east-2.aws.neon.tech:5432/sysventas?sslmode=require

db.username=#neondb_owner#
db.password=#npg_ACP5lMYae1mJ#
# ============================================================
# DDL
# ============================================================
db.ddl.auto=false
db.ddl.script=schema_sv.sql